### ISSUE TITLE
Broken debugger on 2.42.0

### ISSUE THREAD

**Issue by kmanishdisc** [rokucommunity/vscode-brightscript-language#495]
Can't debug variables/continue/step functions. Mix of brs and bs setup. Tried roku's sample code base too. No luck. Downgraded to 2.40.4 and that works fine. used extra key values as described [here](https://github.com/rokucommunity/vscode-brightscript-language/issues/491) . That seems to work

**Comment by DP-Technology-LLC** [comment]
We are seeing the same behavior in 2.43.0.  If we rollback to 2.40.4 as @kmanishdisc did, then the issues go away.  We are using roku-deep-Linking-samples-master for this.

We can set a breakpoint and it will get hit and pause the app, it appears that is the only thing working consistently.

Not Working:

1. Expanding "VARIABLES" (under RUN AND DEBUG) will show "Local".  It will sit there and spin for a moment before finally showing "Invalid string length".  Sometimes just that, sometimes its m: Invalid string length.
2. Under "WATCH" if we add a variable, lets say responseXML, then it will just show responseXML: or it will appear to have the object and when we expand it says [[name]]: Invalid string length.  Sometimes if we have the variable in the list before we start debugging it works as expected.
3. If we click Continue or step over, nothing happens for about 5 seconds then it appears the debugger detaches and the channel remains in a frozen state.

None of these issues happen if we roll back to 2.40.4 (except for the 5 second delay after clicking continue).  2.41.0 runs into issues similar to the above list.

**Comment by TwitchBronBron** [comment]
I believe this issue has been fixed in v2.43.1. Please let us know if that fixes your issue

**Comment by DP-Technology-LLC** [comment]
I can confirm that v2.44.0 doesn't have the issues we were seeing in v2.42 from doing a very brief test.

**Comment by TwitchBronBron** [comment]
@DP-Technology-LLC we've made several improvements to the debugger stability since you last commented. Would you mind testing again and reporting back if you're still encountering these issues?

**Comment by DP-Technology-LLC** [comment]
We are still seeing the same symptoms listed in the [comment from Oct 23](https://github.com/rokucommunity/vscode-brightscript-language/issues/495#issuecomment-1775220044).

The channel we ended up creating is a very simple channel and nowhere near as complex as the deep linking sample.  We have not had any issues debugging our own channel but being unable to debug sample channels from rokudev makes it extremely time consuming to learn new features.
